name: Test workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clojure:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
        
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.5
      with:
        # Install just one or all simultaneously
        cli: 1.10.1.693 # Clojure CLI based on tools.deps

    - name: Prepare dependencies
      run: clj -Sdeps
      
    - name: Run tests
      run: clj -X:test
